export interface CountryConfig {
  code: string;
  name: string;
  flag: string;
  currency: string;
  measurementSystem: "metric" | "imperial";
  dateFormat: string;
  taxIdLabel: string;
  complianceCertLabel: string;
  vehicleInspectionLabel: string;
  postalCodeFormat: string;
  phonePrefix: string;
}

export const COUNTRY_CONFIG: Record<string, CountryConfig> = {
  CA: {
    code: "CA",
    name: "Canada",
    flag: "🇨🇦",
    currency: "CAD",
    measurementSystem: "metric",
    dateFormat: "yyyy-MM-dd",
    taxIdLabel: "GST/HST / BN",
    complianceCertLabel: "Provincial compliance",
    vehicleInspectionLabel: "Safety inspection",
    postalCodeFormat: "A1A 1A1",
    phonePrefix: "+1",
  },
  US: {
    code: "US",
    name: "United States",
    flag: "🇺🇸",
    currency: "USD",
    measurementSystem: "imperial",
    dateFormat: "MM/dd/yyyy",
    taxIdLabel: "EIN",
    complianceCertLabel: "State compliance",
    vehicleInspectionLabel: "State inspection",
    postalCodeFormat: "12345",
    phonePrefix: "+1",
  },
  MX: {
    code: "MX",
    name: "México",
    flag: "🇲🇽",
    currency: "MXN",
    measurementSystem: "metric",
    dateFormat: "dd/MM/yyyy",
    taxIdLabel: "RFC",
    complianceCertLabel: "Cumplimiento fiscal",
    vehicleInspectionLabel: "Verificación vehicular",
    postalCodeFormat: "12345",
    phonePrefix: "+52",
  },
  GB: {
    code: "GB",
    name: "United Kingdom",
    flag: "🇬🇧",
    currency: "GBP",
    measurementSystem: "metric",
    dateFormat: "dd/MM/yyyy",
    taxIdLabel: "VAT Number",
    complianceCertLabel: "Compliance certificate",
    vehicleInspectionLabel: "MOT",
    postalCodeFormat: "SW1A 1AA",
    phonePrefix: "+44",
  },
  ES: {
    code: "ES",
    name: "España",
    flag: "🇪🇸",
    currency: "EUR",
    measurementSystem: "metric",
    dateFormat: "dd/MM/yyyy",
    taxIdLabel: "CIF / NIF",
    complianceCertLabel: "Certificado de conformidad",
    vehicleInspectionLabel: "ITV",
    postalCodeFormat: "12345",
    phonePrefix: "+34",
  },
  FR: {
    code: "FR",
    name: "France",
    flag: "🇫🇷",
    currency: "EUR",
    measurementSystem: "metric",
    dateFormat: "dd/MM/yyyy",
    taxIdLabel: "SIRET / SIREN",
    complianceCertLabel: "Certificat de conformité",
    vehicleInspectionLabel: "Contrôle technique",
    postalCodeFormat: "75001",
    phonePrefix: "+33",
  },
  DE: {
    code: "DE",
    name: "Deutschland",
    flag: "🇩🇪",
    currency: "EUR",
    measurementSystem: "metric",
    dateFormat: "dd.MM.yyyy",
    taxIdLabel: "USt-IdNr.",
    complianceCertLabel: "Konformitätsnachweis",
    vehicleInspectionLabel: "TÜV",
    postalCodeFormat: "12345",
    phonePrefix: "+49",
  },
  IT: {
    code: "IT",
    name: "Italia",
    flag: "🇮🇹",
    currency: "EUR",
    measurementSystem: "metric",
    dateFormat: "dd/MM/yyyy",
    taxIdLabel: "P.IVA / Codice Fiscale",
    complianceCertLabel: "Certificato di conformità",
    vehicleInspectionLabel: "Revisione",
    postalCodeFormat: "00100",
    phonePrefix: "+39",
  },
  PT: {
    code: "PT",
    name: "Portugal",
    flag: "🇵🇹",
    currency: "EUR",
    measurementSystem: "metric",
    dateFormat: "dd/MM/yyyy",
    taxIdLabel: "NIF",
    complianceCertLabel: "Certificado de conformidade",
    vehicleInspectionLabel: "Inspeção periódica",
    postalCodeFormat: "1000-001",
    phonePrefix: "+351",
  },
  NL: {
    code: "NL",
    name: "Nederland",
    flag: "🇳🇱",
    currency: "EUR",
    measurementSystem: "metric",
    dateFormat: "dd-MM-yyyy",
    taxIdLabel: "BTW-nummer",
    complianceCertLabel: "Conformiteitsverklaring",
    vehicleInspectionLabel: "APK",
    postalCodeFormat: "1234 AB",
    phonePrefix: "+31",
  },
  PL: {
    code: "PL",
    name: "Polska",
    flag: "🇵🇱",
    currency: "PLN",
    measurementSystem: "metric",
    dateFormat: "dd.MM.yyyy",
    taxIdLabel: "NIP",
    complianceCertLabel: "Certyfikat zgodności",
    vehicleInspectionLabel: "Przegląd techniczny",
    postalCodeFormat: "00-001",
    phonePrefix: "+48",
  },
  SE: {
    code: "SE",
    name: "Sverige",
    flag: "🇸🇪",
    currency: "SEK",
    measurementSystem: "metric",
    dateFormat: "yyyy-MM-dd",
    taxIdLabel: "Org.nr",
    complianceCertLabel: "Efterlevnadsintyg",
    vehicleInspectionLabel: "Besiktning",
    postalCodeFormat: "123 45",
    phonePrefix: "+46",
  },
  NO: {
    code: "NO",
    name: "Norge",
    flag: "🇳🇴",
    currency: "NOK",
    measurementSystem: "metric",
    dateFormat: "dd.MM.yyyy",
    taxIdLabel: "Org.nr",
    complianceCertLabel: "Samsvarserklæring",
    vehicleInspectionLabel: "EU-kontroll",
    postalCodeFormat: "1234",
    phonePrefix: "+47",
  },
  DK: {
    code: "DK",
    name: "Danmark",
    flag: "🇩🇰",
    currency: "DKK",
    measurementSystem: "metric",
    dateFormat: "dd-MM-yyyy",
    taxIdLabel: "CVR",
    complianceCertLabel: "Overholdelseserklæring",
    vehicleInspectionLabel: "Syn",
    postalCodeFormat: "1234",
    phonePrefix: "+45",
  },
  CH: {
    code: "CH",
    name: "Schweiz",
    flag: "🇨🇭",
    currency: "CHF",
    measurementSystem: "metric",
    dateFormat: "dd.MM.yyyy",
    taxIdLabel: "UID / CHE",
    complianceCertLabel: "Konformitätsbestätigung",
    vehicleInspectionLabel: "MFK",
    postalCodeFormat: "1234",
    phonePrefix: "+41",
  },
  AU: {
    code: "AU",
    name: "Australia",
    flag: "🇦🇺",
    currency: "AUD",
    measurementSystem: "metric",
    dateFormat: "dd/MM/yyyy",
    taxIdLabel: "ABN",
    complianceCertLabel: "Compliance certificate",
    vehicleInspectionLabel: "Roadworthy",
    postalCodeFormat: "2000",
    phonePrefix: "+61",
  },
  NZ: {
    code: "NZ",
    name: "New Zealand",
    flag: "🇳🇿",
    currency: "NZD",
    measurementSystem: "metric",
    dateFormat: "dd/MM/yyyy",
    taxIdLabel: "IRD Number",
    complianceCertLabel: "Compliance certificate",
    vehicleInspectionLabel: "Warrant of fitness",
    postalCodeFormat: "1010",
    phonePrefix: "+64",
  },
  SG: {
    code: "SG",
    name: "Singapore",
    flag: "🇸🇬",
    currency: "SGD",
    measurementSystem: "metric",
    dateFormat: "dd/MM/yyyy",
    taxIdLabel: "UEN",
    complianceCertLabel: "Compliance certificate",
    vehicleInspectionLabel: "Vehicle inspection",
    postalCodeFormat: "123456",
    phonePrefix: "+65",
  },
  JP: {
    code: "JP",
    name: "Japan",
    flag: "🇯🇵",
    currency: "JPY",
    measurementSystem: "metric",
    dateFormat: "yyyy/MM/dd",
    taxIdLabel: "Corporate number",
    complianceCertLabel: "Compliance certificate",
    vehicleInspectionLabel: "Shaken",
    postalCodeFormat: "100-0001",
    phonePrefix: "+81",
  },
  KR: {
    code: "KR",
    name: "South Korea",
    flag: "🇰🇷",
    currency: "KRW",
    measurementSystem: "metric",
    dateFormat: "yyyy-MM-dd",
    taxIdLabel: "Business registration",
    complianceCertLabel: "Compliance certificate",
    vehicleInspectionLabel: "Vehicle inspection",
    postalCodeFormat: "12345",
    phonePrefix: "+82",
  },
  IN: {
    code: "IN",
    name: "India",
    flag: "🇮🇳",
    currency: "INR",
    measurementSystem: "metric",
    dateFormat: "dd/MM/yyyy",
    taxIdLabel: "GSTIN",
    complianceCertLabel: "Compliance certificate",
    vehicleInspectionLabel: "PUC / fitness",
    postalCodeFormat: "110001",
    phonePrefix: "+91",
  },
  ZA: {
    code: "ZA",
    name: "South Africa",
    flag: "🇿🇦",
    currency: "ZAR",
    measurementSystem: "metric",
    dateFormat: "yyyy/MM/dd",
    taxIdLabel: "VAT / registration",
    complianceCertLabel: "Compliance certificate",
    vehicleInspectionLabel: "Roadworthy",
    postalCodeFormat: "0001",
    phonePrefix: "+27",
  },
};

const DEFAULT_COUNTRY = "CA";

export function getCountryConfig(countryCode: string): CountryConfig {
  const upper = (countryCode || "").toUpperCase();
  return COUNTRY_CONFIG[upper] ?? COUNTRY_CONFIG[DEFAULT_COUNTRY];
}
