import type { FormTemplate } from "@/types/forms";
import { SPRINT_B_FORM_TEMPLATES } from "@/lib/formTemplatesSprintB";

/** Base + regional MachinPro form templates (`name`, `description`, labels are i18n keys). */
export const INITIAL_FORM_TEMPLATES: FormTemplate[] = [
  {
    id: "tpl-tailgate-001",
    name: "form_tpl_daily_safety_name",
    description: "form_tpl_daily_safety_desc",
    region: ["GLOBAL"],
    category: "form_cat_meeting",
    isBase: true,
    requiresAllSignatures: true,
    expiresInHours: 24,
    createdAt: "2026-01-01T00:00:00Z",
    createdBy: "machinpro",
    language: "en",
    sections: [
      {
        id: "dsm_general",
        title: "form_sec_general",
        fields: [
          {
            id: "dsm_project",
            type: "text",
            label: "form_lbl_project",
            required: true,
          },
          {
            id: "dsm_date",
            type: "date",
            label: "form_lbl_date",
            required: true,
          },
          {
            id: "dsm_supervisor",
            type: "select",
            label: "form_lbl_supervisor",
            required: true,
            options: [],
            formRole: "supervisor_display",
          },
          {
            id: "dsm_start",
            type: "time",
            label: "form_lbl_start_time",
            required: true,
          },
        ],
      },
      {
        id: "dsm_plan",
        title: "form_sec_work_plan",
        fields: [
          {
            id: "dsm_topics",
            type: "multiselect",
            label: "form_lbl_topics",
            required: true,
            options: [
              "form_opt_topic_general",
              "form_opt_topic_heights",
              "form_opt_topic_hazmat",
              "form_opt_topic_equipment",
              "form_opt_topic_fire",
              "form_opt_topic_first_aid",
              "form_opt_topic_other",
            ],
          },
          {
            id: "dsm_plan_text",
            type: "textarea",
            label: "form_lbl_today_plan",
            required: true,
          },
          {
            id: "dsm_hazards",
            type: "textarea",
            label: "form_lbl_hazards",
            required: false,
          },
          {
            id: "dsm_controls",
            type: "textarea",
            label: "form_lbl_controls",
            required: false,
          },
        ],
      },
      {
        id: "dsm_att",
        title: "form_sec_attendance",
        fields: [
          {
            id: "dsm_attendance",
            type: "attendance",
            label: "form_lbl_attendees",
            required: true,
          },
          {
            id: "dsm_photo",
            type: "photo",
            label: "form_lbl_photos_optional",
            required: false,
          },
        ],
      },
      {
        id: "dsm_close",
        title: "form_sec_signoff",
        fields: [
          {
            id: "dsm_sig",
            type: "signature",
            label: "form_lbl_supervisor_sig",
            required: true,
            formRole: "supervisor_signature",
          },
        ],
      },
    ],
  },
  {
    id: "tpl-incident-report",
    name: "form_tpl_incident_name",
    description: "form_tpl_incident_desc",
    region: ["GLOBAL"],
    category: "form_cat_report",
    isBase: true,
    requiresAllSignatures: false,
    expiresInHours: 24,
    createdAt: "2026-01-01T00:00:00Z",
    createdBy: "machinpro",
    language: "en",
    sections: [
      {
        id: "inc_gen",
        title: "form_sec_general",
        fields: [
          {
            id: "inc_project",
            type: "text",
            label: "form_lbl_project",
            required: true,
          },
          {
            id: "inc_date",
            type: "date",
            label: "form_lbl_date",
            required: true,
          },
          {
            id: "inc_time",
            type: "time",
            label: "form_lbl_time",
            required: true,
          },
          {
            id: "inc_type",
            type: "select",
            label: "form_lbl_incident_type",
            required: true,
            options: [
              "form_opt_inc_accident",
              "form_opt_inc_near_miss",
              "form_opt_inc_property",
              "form_opt_inc_environmental",
            ],
          },
        ],
      },
      {
        id: "inc_detail",
        title: "form_sec_details",
        fields: [
          {
            id: "inc_persons",
            type: "text",
            label: "form_lbl_persons_involved",
            required: true,
          },
          {
            id: "inc_desc",
            type: "textarea",
            label: "form_lbl_description",
            required: true,
          },
          {
            id: "inc_actions",
            type: "textarea",
            label: "form_lbl_immediate_actions",
            required: false,
          },
          {
            id: "inc_photo",
            type: "photo",
            label: "form_lbl_photos",
            required: false,
          },
        ],
      },
      {
        id: "inc_sign",
        title: "form_sec_signoff",
        fields: [
          {
            id: "inc_sig",
            type: "signature",
            label: "form_lbl_reporter_sig",
            required: true,
            formRole: "supervisor_signature",
          },
        ],
      },
    ],
  },
  {
    id: "tpl-equipment-001",
    name: "form_tpl_preuse_name",
    description: "form_tpl_preuse_desc",
    region: ["GLOBAL"],
    category: "form_cat_inspection",
    isBase: true,
    requiresAllSignatures: false,
    expiresInHours: 24,
    createdAt: "2026-01-01T00:00:00Z",
    createdBy: "machinpro",
    language: "en",
    sections: [
      {
        id: "pui_info",
        title: "form_sec_equipment",
        fields: [
          {
            id: "pui_equipment",
            type: "text",
            label: "form_lbl_equipment_id",
            required: true,
          },
          {
            id: "pui_project",
            type: "text",
            label: "form_lbl_project",
            required: true,
          },
          {
            id: "pui_date",
            type: "date",
            label: "form_lbl_date",
            required: true,
          },
          {
            id: "pui_inspector",
            type: "select",
            label: "form_lbl_inspector",
            required: true,
            options: [],
          },
          {
            id: "pui_unit",
            type: "text",
            label: "form_lbl_vehicle_unit",
            required: false,
          },
        ],
      },
      {
        id: "pui_matrix",
        title: "form_sec_checklist",
        fields: [
          {
            id: "pui_table",
            type: "inspection_table",
            label: "form_lbl_inspection_matrix",
            required: true,
            options: ["pass", "fail", "na"],
            rows: [
              { id: "r_brakes", label: "form_insp_row_brakes" },
              { id: "r_tires", label: "form_insp_row_tires" },
              { id: "r_lights", label: "form_insp_row_lights" },
              { id: "r_hydraulics", label: "form_insp_row_hydraulics" },
              { id: "r_steering", label: "form_insp_row_steering" },
              { id: "r_guards", label: "form_insp_row_guards" },
            ],
            columns: [
              {
                id: "status",
                label: "form_insp_col_status",
                kind: "select",
              },
              {
                id: "notes",
                label: "form_insp_col_notes",
                kind: "text",
              },
            ],
          },
          {
            id: "pui_photo",
            type: "photo",
            label: "form_lbl_photos",
            required: false,
          },
        ],
      },
      {
        id: "pui_sign",
        title: "form_sec_signoff",
        fields: [
          {
            id: "pui_sig",
            type: "signature",
            label: "form_lbl_inspector_sig",
            required: true,
            formRole: "supervisor_signature",
          },
        ],
      },
    ],
  },
  {
    id: "tpl-height-permit",
    name: "form_tpl_height_name",
    description: "form_tpl_height_desc",
    region: ["GLOBAL"],
    category: "form_cat_permit",
    isBase: true,
    requiresAllSignatures: false,
    expiresInHours: 12,
    createdAt: "2026-01-01T00:00:00Z",
    createdBy: "machinpro",
    language: "en",
    sections: [
      {
        id: "hap_info",
        title: "form_sec_permit",
        fields: [
          {
            id: "hap_project",
            type: "text",
            label: "form_lbl_project",
            required: true,
          },
          {
            id: "hap_date",
            type: "date",
            label: "form_lbl_date",
            required: true,
          },
          {
            id: "hap_supervisor",
            type: "select",
            label: "form_lbl_supervisor",
            required: true,
            options: [],
            formRole: "supervisor_display",
          },
          {
            id: "hap_task",
            type: "textarea",
            label: "form_lbl_height_task",
            required: true,
          },
          {
            id: "hap_duration",
            type: "text",
            label: "form_lbl_estimated_duration",
            required: false,
          },
        ],
      },
      {
        id: "hap_safety",
        title: "form_sec_controls",
        fields: [
          {
            id: "hap_rescue",
            type: "textarea",
            label: "form_lbl_rescue_plan",
            required: true,
          },
          {
            id: "hap_equipment",
            type: "textarea",
            label: "form_lbl_ppe_equipment",
            required: true,
          },
          {
            id: "hap_photo",
            type: "photo",
            label: "form_lbl_photos_optional",
            required: false,
          },
        ],
      },
      {
        id: "hap_sign",
        title: "form_sec_signoff",
        fields: [
          {
            id: "hap_sig",
            type: "signature",
            label: "form_lbl_authorized_sig",
            required: true,
            formRole: "supervisor_signature",
          },
        ],
      },
    ],
  },
  {
    id: "tpl-whmis",
    name: "form_tpl_whmis_name",
    description: "form_tpl_whmis_desc",
    region: ["CA", "US"],
    category: "form_cat_training",
    isBase: true,
    requiresAllSignatures: false,
    expiresInHours: 24,
    createdAt: "2026-01-01T00:00:00Z",
    createdBy: "machinpro",
    language: "en",
    sections: [
      {
        id: "whm_body",
        title: "form_sec_whmis",
        fields: [
          {
            id: "whm_project",
            type: "text",
            label: "form_lbl_project",
            required: true,
          },
          {
            id: "whm_date",
            type: "date",
            label: "form_lbl_date",
            required: true,
          },
          {
            id: "whm_review",
            type: "textarea",
            label: "form_lbl_whmis_review",
            required: true,
          },
          {
            id: "whm_sds",
            type: "radio",
            label: "form_lbl_sds_available",
            required: true,
            options: ["form_opt_yes", "form_opt_no", "form_opt_na"],
          },
        ],
      },
      {
        id: "whm_sign",
        title: "form_sec_signoff",
        fields: [
          {
            id: "whm_sig",
            type: "signature",
            label: "form_lbl_worker_sig",
            required: true,
            formRole: "supervisor_signature",
          },
        ],
      },
    ],
  },
  {
    id: "tpl-loto",
    name: "form_tpl_loto_name",
    description: "form_tpl_loto_desc",
    region: ["CA", "US"],
    category: "form_cat_loto",
    isBase: true,
    requiresAllSignatures: false,
    expiresInHours: 8,
    createdAt: "2026-01-01T00:00:00Z",
    createdBy: "machinpro",
    language: "en",
    sections: [
      {
        id: "loto_body",
        title: "form_sec_loto",
        fields: [
          {
            id: "loto_project",
            type: "text",
            label: "form_lbl_project",
            required: true,
          },
          {
            id: "loto_equipment",
            type: "text",
            label: "form_lbl_equipment_id",
            required: true,
          },
          {
            id: "loto_procedure",
            type: "textarea",
            label: "form_lbl_loto_procedure",
            required: true,
          },
          {
            id: "loto_isolated",
            type: "radio",
            label: "form_lbl_energy_isolated",
            required: true,
            options: ["form_opt_yes", "form_opt_no"],
          },
        ],
      },
      {
        id: "loto_sign",
        title: "form_sec_signoff",
        fields: [
          {
            id: "loto_sig",
            type: "signature",
            label: "form_lbl_authorized_sig",
            required: true,
            formRole: "supervisor_signature",
          },
        ],
      },
    ],
  },
  {
    id: "tpl-prl-brief",
    name: "form_tpl_prl_name",
    description: "form_tpl_prl_desc",
    region: ["ES", "EU"],
    category: "form_cat_prl",
    isBase: true,
    requiresAllSignatures: false,
    expiresInHours: 24,
    createdAt: "2026-01-01T00:00:00Z",
    createdBy: "machinpro",
    language: "en",
    sections: [
      {
        id: "prl_body",
        title: "form_sec_prl",
        fields: [
          {
            id: "prl_project",
            type: "text",
            label: "form_lbl_project",
            required: true,
          },
          {
            id: "prl_date",
            type: "date",
            label: "form_lbl_date",
            required: true,
          },
          {
            id: "prl_training",
            type: "textarea",
            label: "form_lbl_prl_training_ref",
            required: true,
          },
          {
            id: "prl_risk",
            type: "select",
            label: "form_lbl_risk_level",
            required: true,
            options: [
              "form_opt_risk_low",
              "form_opt_risk_medium",
              "form_opt_risk_high",
            ],
          },
        ],
      },
      {
        id: "prl_sign",
        title: "form_sec_signoff",
        fields: [
          {
            id: "prl_sig",
            type: "signature",
            label: "form_lbl_worker_sig",
            required: true,
            formRole: "supervisor_signature",
          },
        ],
      },
    ],
  },
  {
    id: "tpl-rams",
    name: "form_tpl_rams_name",
    description: "form_tpl_rams_desc",
    region: ["GB", "UK"],
    category: "form_cat_rams",
    isBase: true,
    requiresAllSignatures: false,
    expiresInHours: 24,
    createdAt: "2026-01-01T00:00:00Z",
    createdBy: "machinpro",
    language: "en",
    sections: [
      {
        id: "rams_body",
        title: "form_sec_rams",
        fields: [
          {
            id: "rams_project",
            type: "text",
            label: "form_lbl_project",
            required: true,
          },
          {
            id: "rams_ref",
            type: "text",
            label: "form_lbl_rams_reference",
            required: true,
          },
          {
            id: "rams_scope",
            type: "textarea",
            label: "form_lbl_work_scope",
            required: true,
          },
          {
            id: "rams_controls",
            type: "textarea",
            label: "form_lbl_controls",
            required: true,
          },
        ],
      },
      {
        id: "rams_sign",
        title: "form_sec_signoff",
        fields: [
          {
            id: "rams_sig",
            type: "signature",
            label: "form_lbl_supervisor_sig",
            required: true,
            formRole: "supervisor_signature",
          },
        ],
      },
    ],
  },
  {
    id: "tpl-ats",
    name: "form_tpl_ats_name",
    description: "form_tpl_ats_desc",
    region: ["MX", "LATAM"],
    category: "form_cat_ats",
    isBase: true,
    requiresAllSignatures: false,
    expiresInHours: 12,
    createdAt: "2026-01-01T00:00:00Z",
    createdBy: "machinpro",
    language: "en",
    sections: [
      {
        id: "ats_body",
        title: "form_sec_ats",
        fields: [
          {
            id: "ats_project",
            type: "text",
            label: "form_lbl_project",
            required: true,
          },
          {
            id: "ats_date",
            type: "date",
            label: "form_lbl_date",
            required: true,
          },
          {
            id: "ats_type",
            type: "select",
            label: "form_lbl_ats_work_type",
            required: true,
            options: [
              "form_opt_ats_scaffold",
              "form_opt_ats_ladder",
              "form_opt_ats_lifting",
              "form_opt_ats_roof",
              "form_opt_ats_other",
            ],
          },
          {
            id: "ats_controls",
            type: "textarea",
            label: "form_lbl_prevention_measures",
            required: true,
          },
        ],
      },
      {
        id: "ats_sign",
        title: "form_sec_signoff",
        fields: [
          {
            id: "ats_sig",
            type: "signature",
            label: "form_lbl_responsible_sig",
            required: true,
            formRole: "supervisor_signature",
          },
        ],
      },
    ],
  },
  ...SPRINT_B_FORM_TEMPLATES,
  {
    id: "tpl-blank-custom",
    name: "form_blank_custom_name",
    description: "form_blank_custom_desc",
    region: ["GLOBAL"],
    category: "form_cat_custom",
    isBase: true,
    requiresAllSignatures: false,
    expiresInHours: 72,
    createdAt: "2026-01-01T00:00:00Z",
    createdBy: "machinpro",
    language: "en",
    sections: [
      {
        id: "blank_main",
        title: "form_sec_general",
        fields: [
          {
            id: "blank_project",
            type: "text",
            label: "form_lbl_project",
            required: true,
          },
          {
            id: "blank_date",
            type: "date",
            label: "form_lbl_date",
            required: true,
          },
          {
            id: "blank_details",
            type: "textarea",
            label: "form_lbl_description",
            required: false,
          },
        ],
      },
    ],
  },
];
