import { jsPDF } from "jspdf";
import type { PayrollDeduction } from "@/lib/payroll";
import { drawMachinProPdfFooter, drawPdfBrandedHeader } from "@/lib/pdfBranding";
import { fileSlugCompany, filenameDateYmd } from "@/lib/csvExport";

export type PayrollPdfRow = {
  employeeName: string;
  hours: number;
  gross: number;
  totalDeductions: number;
  net: number;
  employerCost: number;
  deductions: PayrollDeduction[];
};

function L(labels: Record<string, string>, key: string, fallback: string): string {
  const v = labels[key];
  return typeof v === "string" && v.trim() ? v : fallback;
}

export async function generatePayrollPdf(opts: {
  labels: Record<string, string>;
  companyName: string;
  companyId: string;
  companyLogoUrl?: string | null;
  periodStart: string;
  periodEnd: string;
  currency: string;
  rows: PayrollPdfRow[];
}): Promise<{ blob: Blob; filename: string }> {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const R = (k: string, fb: string) => L(opts.labels, k, fb);

  let y = await drawPdfBrandedHeader(doc, { companyLogoUrl: opts.companyLogoUrl });

  doc.setFontSize(15);
  doc.setFont("helvetica", "bold");
  doc.text(R("payroll_title", "Payroll"), 105, y, { align: "center" });
  y += 8;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(opts.companyName, 14, y);
  y += 5;
  doc.text(`${R("timesheet_date_from", "From")}: ${opts.periodStart}  →  ${R("timesheet_date_to", "To")}: ${opts.periodEnd}`, 14, y);
  y += 8;

  let sumNet = 0;
  let sumEmployer = 0;

  const ensure = (need: number) => {
    if (y + need > 275) {
      doc.addPage();
      y = 20;
    }
  };

  for (const r of opts.rows) {
    sumNet += r.net;
    sumEmployer += r.employerCost;
    ensure(28);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.text(r.employeeName, 14, y);
    y += 5;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text(`${R("timesheet_hours", "Hours")}: ${r.hours.toFixed(1)}`, 14, y);
    y += 4;
    doc.text(`${R("payroll_gross", "Gross")}: ${opts.currency} ${r.gross.toFixed(2)}`, 14, y);
    y += 4;
    doc.setFont("helvetica", "bold");
    doc.text(R("payroll_deductions", "Deductions"), 14, y);
    y += 4;
    doc.setFont("helvetica", "normal");
    for (const d of r.deductions) {
      ensure(5);
      const tag = d.isEmployer ? ` ${R("payroll_deduction_employer_tag", "(employer)")}` : "";
      const dn = R(d.nameKey, d.name);
      doc.text(`• ${dn}${tag}: ${(d.rate * 100).toFixed(2)}% → ${d.amount.toFixed(2)}`, 18, y);
      y += 3.5;
    }
    doc.setFont("helvetica", "bold");
    doc.text(`${R("payroll_net", "Net")}: ${opts.currency} ${r.net.toFixed(2)}`, 14, y);
    y += 4;
    if (r.employerCost > 0) {
      doc.setFont("helvetica", "normal");
      doc.text(`${R("payroll_employer_cost", "Employer cost")}: ${opts.currency} ${r.employerCost.toFixed(2)}`, 14, y);
      y += 4;
    }
    y += 3;
    doc.setDrawColor(220);
    doc.line(14, y, 196, y);
    y += 5;
  }

  ensure(16);
  doc.setFontSize(9);
  doc.setTextColor(90);
  const note = doc.splitTextToSize(
    R("payroll_orientative_note", "Deductions are indicative."),
    182
  );
  for (const ln of note) {
    doc.text(ln, 14, y);
    y += 4;
  }
  doc.setTextColor(0);
  y += 2;

  ensure(10);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(
    `${R("payroll_pdf_company_total", "Company total")}: ${opts.currency} ${(sumNet + sumEmployer).toFixed(2)}`,
    14,
    y
  );
  y += 4;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(`(${R("payroll_pdf_nets_plus_employer", "Sum of net pays + employer costs")})`, 14, y);

  drawMachinProPdfFooter(doc, R("forms_pdf_footer", "Generated by MachinPro"));

  const slug = fileSlugCompany(opts.companyName, opts.companyId || "co");
  return {
    blob: doc.output("blob"),
    filename: `payroll_${slug}_${filenameDateYmd()}.pdf`,
  };
}
