import { jsPDF } from "jspdf";
import { drawMachinProPdfFooter, drawPdfBrandedHeader } from "@/lib/pdfBranding";

export type WorkOrderPdfLine = {
  taskName: string;
  unitLabel: string;
  currency: string;
  catalogCost: number;
  catalogSell: number;
  effCost: number;
  effSell: number;
  hasCostOverride: boolean;
  hasSellOverride: boolean;
};

function L(labels: Record<string, string>, key: string, fallback: string): string {
  const v = labels[key];
  return typeof v === "string" && v.trim() ? v : fallback;
}

function fmtPrice(currency: string, n: number): string {
  return `${currency} ${n.toFixed(4)}`;
}

export async function generateWorkOrderPdf(opts: {
  labels: Record<string, string>;
  companyName: string;
  companyLogoUrl?: string | null;
  companyAddress?: string | null;
  projectName: string;
  projectAddress?: string | null;
  reportDate: string;
  lines: WorkOrderPdfLine[];
  totalSell: number;
}): Promise<Blob> {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const labels = opts.labels;
  const R = (k: string, fb: string) => L(labels, k, fb);

  let y = await drawPdfBrandedHeader(doc, { companyLogoUrl: opts.companyLogoUrl });

  doc.setFontSize(15);
  doc.setFont("helvetica", "bold");
  doc.text(R("work_order_title", "Work order"), 105, y, { align: "center" });
  y += 8;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(opts.companyName, 14, y);
  y += 5;
  const addr = (opts.companyAddress ?? "").trim();
  if (addr) {
    const addrLines = doc.splitTextToSize(addr, 182);
    for (const ln of addrLines) {
      doc.text(ln, 14, y);
      y += 4;
    }
  }
  doc.setFont("helvetica", "bold");
  doc.text(`${R("project", "Project")}: ${opts.projectName}`, 14, y);
  y += 5;
  doc.setFont("helvetica", "normal");
  const ploc = (opts.projectAddress ?? "").trim();
  if (ploc) {
    const locLines = doc.splitTextToSize(ploc, 182);
    for (const ln of locLines) {
      doc.text(ln, 14, y);
      y += 4;
    }
  }
  doc.text(`${R("date", "Date")}: ${opts.reportDate}`, 14, y);
  y += 8;

  const colTask = 14;
  const colUnit = 78;
  const colCost = 102;
  const colSell = 132;
  const colAdj = 158;

  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text(R("production_catalog_name", "Task"), colTask, y);
  doc.text(R("production_catalog_unit", "Unit"), colUnit, y);
  doc.text(R("production_catalog_cost_price", "Cost"), colCost, y);
  doc.text(R("production_catalog_sell_price", "Sell"), colSell, y);
  doc.text(R("work_order_pdf_adjusted", "Adjusted"), colAdj, y);
  y += 5;
  doc.setFont("helvetica", "normal");
  doc.setDrawColor(200);
  doc.line(14, y, 196, y);
  y += 4;

  const ensure = (need: number) => {
    if (y + need > 270) {
      doc.addPage();
      y = 20;
    }
  };

  for (const row of opts.lines) {
    ensure(14);
    const taskLines = doc.splitTextToSize(row.taskName, 60);
    let rowY = y;
    for (const tl of taskLines) {
      doc.text(tl, colTask, rowY);
      rowY += 3.5;
    }
    doc.text(row.unitLabel, colUnit, y);
    doc.text(fmtPrice(row.currency, row.catalogCost), colCost, y);
    doc.text(fmtPrice(row.currency, row.catalogSell), colSell, y);
    let adj = "—";
    if (row.hasCostOverride || row.hasSellOverride) {
      const parts: string[] = [];
      if (row.hasCostOverride) parts.push(`C ${fmtPrice(row.currency, row.effCost)}`);
      if (row.hasSellOverride) parts.push(`S ${fmtPrice(row.currency, row.effSell)}`);
      adj = parts.join("\n");
    }
    const adjLines = doc.splitTextToSize(adj, 38);
    let ay = y;
    for (const al of adjLines) {
      doc.text(al, colAdj, ay);
      ay += 3.5;
    }
    y = Math.max(rowY, ay) + 3;
  }

  ensure(10);
  doc.setFont("helvetica", "bold");
  const cur0 = opts.lines[0]?.currency ?? "";
  doc.text(
    `${R("work_order_total", "Estimated total")}: ${cur0} ${opts.totalSell.toFixed(4)}`,
    14,
    y
  );
  y += 12;

  ensure(28);
  doc.setFont("helvetica", "normal");
  doc.text(R("work_order_pdf_client_signature", "Client signature"), 14, y);
  y += 6;
  doc.setDrawColor(80);
  doc.line(14, y, 120, y);
  y += 4;
  doc.setFontSize(8);
  doc.setTextColor(100);
  doc.text(R("work_order_pdf_sign_hint", "Sign and date after review"), 14, y);
  doc.setTextColor(0);

  drawMachinProPdfFooter(doc, R("forms_pdf_footer", "Generated by MachinPro"));
  return doc.output("blob");
}
