import type { ProjectPhoto } from "@/lib/useProjectPhotos";
import { formatDateTime, resolveUserTimezone } from "@/lib/dateUtils";

export type PhotoReportSortBy = "date_desc" | "date_asc" | "category" | "author";
export type PhotoReportPhotosPerPage = 1 | 2 | 4;
export type PhotoReportPhotoSize = "large" | "medium" | "small";
export type PhotoReportOrientation = "portrait" | "landscape";

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function localeForLanguage(lang?: string): string {
  const m: Record<string, string> = {
    es: "es-ES",
    en: "en-GB",
    fr: "fr-FR",
    de: "de-DE",
    it: "it-IT",
    pt: "pt-PT",
  };
  return m[lang ?? "es"] ?? "en-GB";
}

function chunk<T>(arr: T[], size: number): T[][] {
  const out: T[][] = [];
  for (let i = 0; i < arr.length; i += size) out.push(arr.slice(i, i + size));
  return out;
}

function sortPhotos(photos: ProjectPhoto[], sortBy: PhotoReportSortBy): ProjectPhoto[] {
  const copy = [...photos];
  const catOrder = (c: ProjectPhoto["photo_category"]) =>
    c === "progress" ? 0 : c === "incident" ? 1 : 2;
  switch (sortBy) {
    case "date_desc":
      return copy.sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime());
    case "date_asc":
      return copy.sort((a, b) => new Date(a.created_at).getTime() - new Date(b.created_at).getTime());
    case "category":
      return copy.sort((a, b) => {
        const d = catOrder(a.photo_category) - catOrder(b.photo_category);
        if (d !== 0) return d;
        return new Date(a.created_at).getTime() - new Date(b.created_at).getTime();
      });
    case "author":
      return copy.sort((a, b) =>
        (a.submitted_by_name ?? "").localeCompare(b.submitted_by_name ?? "", undefined, { sensitivity: "base" })
      );
    default:
      return copy;
  }
}

function photoSizePx(size: PhotoReportPhotoSize): number {
  if (size === "medium") return 300;
  if (size === "small") return 200;
  return 500;
}

export async function generatePhotoReport(params: {
  photos: ProjectPhoto[];
  projectName: string;
  companyName: string;
  companyLogoUrl?: string;
  generatedBy: string;
  dateRange?: { from: string; to: string };
  language?: string;
  labels: Record<string, string>;
  sortBy?: PhotoReportSortBy;
  photosPerPage?: PhotoReportPhotosPerPage;
  photoSize?: PhotoReportPhotoSize;
  includeGps?: boolean;
  includeAuthor?: boolean;
  includeDate?: boolean;
  includeNotes?: boolean;
  orientation?: PhotoReportOrientation;
  dateLocaleBcp47?: string;
  timeZone?: string;
}): Promise<void> {
  const {
    photos: rawPhotos,
    projectName,
    companyName,
    companyLogoUrl,
    generatedBy,
    dateRange,
    language,
    labels: t,
    sortBy = "date_desc",
    photosPerPage = 1,
    photoSize = "large",
    includeGps = true,
    includeAuthor = true,
    includeDate = true,
    includeNotes = true,
    orientation = "portrait",
    dateLocaleBcp47,
    timeZone: timeZoneParam,
  } = params;

  const photos = sortPhotos(rawPhotos, sortBy);
  const chunks = chunk(photos, photosPerPage);
  const maxImgH = photoSizePx(photoSize);
  const compact = photosPerPage > 1;
  const compactImgH = compact ? Math.min(maxImgH, photosPerPage === 2 ? 320 : 200) : maxImgH;

  const locale = dateLocaleBcp47 ?? localeForLanguage(language);
  const tz = timeZoneParam ?? resolveUserTimezone(null);
  const now = new Date();
  const generatedOnStr = formatDateTime(now, locale, tz);
  const title = t.photoReport ?? "Site Photo Report";
  const genBy = t.generatedBy ?? "Generated by";
  const genOn = t.generatedOn ?? "Generation date";
  const viewMap = t.viewOnMap ?? "View on map";
  const gpsLabel = t.gpsLocation ?? "GPS Location";
  const pageOf = t.pageOf ?? "of";
  const amber = "#b45309";
  const totalPages = photos.length === 0 ? 2 : 1 + chunks.length;

  const categoryLabel = (cat: ProjectPhoto["photo_category"]) => {
    if (cat === "progress") return t.photoProgress ?? "Progress";
    if (cat === "incident") return t.photoIncident ?? "Incident";
    return t.photoHealthSafety ?? "H&S";
  };

  const categoryBadgeStyle = (cat: ProjectPhoto["photo_category"]) => {
    if (cat === "progress") return "background:#dcfce7;color:#166534;";
    if (cat === "incident") return "background:#fee2e2;color:#991b1b;";
    return "background:#dbeafe;color:#1e40af;";
  };

  const statusLabel = (st: ProjectPhoto["status"]) => {
    if (st === "approved") return t.photoStatusApproved ?? "Approved";
    if (st === "rejected") return t.photoStatusRejected ?? "Rejected";
    return t.photoStatusPending ?? "Pending";
  };

  const footerLine = `${escapeHtml(companyName)} · MachinPro`;
  const toolbarTitle = escapeHtml(t.photoReport ?? "MachinPro · Reporte de Fotos");
  const printLabel = escapeHtml(t.printReport ?? "Print / Save PDF");
  const closeLabel = escapeHtml(t.whClose ?? "Close");

  const renderPhotoInner = (photo: ProjectPhoto, seq: number): string => {
    const created = new Date(photo.created_at);
    const when = formatDateTime(created, locale, tz);
    const cat = photo.photo_category;
    const mapUrl =
      photo.gps_lat != null && photo.gps_lng != null
        ? `https://maps.google.com/?q=${encodeURIComponent(`${photo.gps_lat},${photo.gps_lng}`)}`
        : null;
    const coords =
      photo.gps_lat != null && photo.gps_lng != null
        ? `${photo.gps_lat.toFixed(6)}, ${photo.gps_lng.toFixed(6)}${
            photo.gps_accuracy != null ? ` (±${Math.round(photo.gps_accuracy)}m)` : ""
          }`
        : null;

    const authorLine =
      includeAuthor
        ? `<p class="line"><strong>${escapeHtml(t.photoUploadedBy ?? "Uploaded by")}:</strong> ${escapeHtml(photo.submitted_by_name ?? "—")}</p>`
        : "";
    const dateLine = includeDate ? `<p class="line">${escapeHtml(when)}</p>` : "";
    const gpsBlock =
      includeGps && coords && mapUrl
        ? `<p class="line"><strong>${escapeHtml(gpsLabel)}:</strong> ${escapeHtml(coords)} · <a href="${mapUrl.replace(/"/g, "&quot;")}" target="_blank" rel="noopener noreferrer">${escapeHtml(viewMap)}</a></p>`
        : "";
    const notesBlock =
      includeNotes && photo.notes
        ? `<p class="notes">${escapeHtml(photo.notes)}</p>`
        : "";
    const weatherBlock =
      includeNotes && photo.weather_conditions
        ? `<p class="line"><strong>${escapeHtml(t.reportWeather ?? "Weather")}:</strong> ${escapeHtml(photo.weather_conditions)}</p>`
        : "";
    const tagsBlock =
      includeNotes && photo.tags?.length
        ? `<p class="line"><strong>${escapeHtml(t.reportTags ?? "Tags")}:</strong> ${escapeHtml(photo.tags.join(", "))}</p>`
        : "";

    const sigBlock =
      photo.signature_url
        ? `<div class="sig-block"><p class="line"><strong>${escapeHtml(t.reportSignature ?? "Signature")}</strong></p>
           ${photo.signature_by ? `<p class="line">${escapeHtml(photo.signature_by)}</p>` : ""}
           ${photo.signature_at ? `<p class="line">${escapeHtml(formatDateTime(photo.signature_at, locale, tz))}</p>` : ""}
           <img class="sig-img" src="${escapeHtml(photo.signature_url)}" alt="" /></div>`
        : "";

    const imgClass = compact ? "photo-img photo-img-compact" : "photo-img";
    const h = compact ? compactImgH : maxImgH;

    return `
      <div class="photo-cell-inner">
        <p class="seq">#${seq}</p>
        <div class="img-wrap">
          <img class="${imgClass}" style="max-height:${h}px" src="${escapeHtml(photo.photo_url)}" alt="" crossorigin="anonymous" />
        </div>
        <p class="badges">
          <span class="badge" style="${categoryBadgeStyle(cat)}">${escapeHtml(categoryLabel(cat))}</span>
          <span class="badge status">${escapeHtml(statusLabel(photo.status))}</span>
        </p>
        ${authorLine}
        ${dateLine}
        ${gpsBlock}
        ${notesBlock}
        ${weatherBlock}
        ${tagsBlock}
        ${sigBlock}
        ${compact ? "" : '<hr class="sep" />'}
      </div>`;
  };

  let globalSeq = 0;
  const photoPagesHtml = chunks
    .map((group, chunkIdx) => {
      const cells = group
        .map((photo) => {
          globalSeq += 1;
          return `<div class="photo-cell">${renderPhotoInner(photo, globalSeq)}</div>`;
        })
        .join("");

      const gridClass =
        photosPerPage === 4 ? "photo-grid photo-grid-4" : photosPerPage === 2 ? "photo-grid photo-grid-2" : "photo-grid photo-grid-1";

      const pageIdx = chunkIdx + 2;
      return `
    <div class="page photo-page">
      <div class="photo-inner ${gridClass}">
        ${cells}
      </div>
      <footer class="page-footer"><span>${footerLine}</span><span class="page-num">${pageIdx} ${pageOf} ${totalPages}</span></footer>
    </div>`;
    })
    .join("");

  const emptyPage =
    photos.length === 0
      ? `
    <div class="page photo-page">
      <div class="photo-inner">
        <p class="line">${escapeHtml(t.noApprovedPhotos ?? "No photos")}</p>
      </div>
      <footer class="page-footer"><span>${footerLine}</span><span class="page-num">2 ${pageOf} ${totalPages}</span></footer>
    </div>`
      : "";

  const coverHtml = `
    <div class="page cover cover-page">
      <div class="cover-inner">
        ${companyLogoUrl ? `<img class="logo" src="${escapeHtml(companyLogoUrl)}" alt="" crossorigin="anonymous" />` : ""}
        <h1 class="company">${escapeHtml(companyName)}</h1>
        <p class="machin-stamp" style="color:${amber};">MachinPro</p>
        <h2 class="report-title">${escapeHtml(title)}</h2>
        <p class="project-line"><strong>${escapeHtml(projectName)}</strong></p>
        <p class="meta">${escapeHtml(genOn)}: ${escapeHtml(generatedOnStr)}</p>
        <p class="meta">${escapeHtml(genBy)}: ${escapeHtml(generatedBy)}</p>
        ${
          dateRange
            ? `<p class="meta">${escapeHtml(dateRange.from)} — ${escapeHtml(dateRange.to)}</p>`
            : ""
        }
      </div>
      <footer class="page-footer"><span>${footerLine}</span><span class="page-num">1 ${pageOf} ${totalPages}</span></footer>
    </div>`;

  const pageSize = orientation === "landscape" ? "A4 landscape" : "A4 portrait";

  const toolbarHtml = `
  <div class="print-toolbar">
    <span class="print-toolbar-brand">${toolbarTitle}</span>
    <div class="print-toolbar-actions">
      <button type="button" class="print-btn print-btn-primary" onclick="window.print()">${printLabel}</button>
      <button type="button" class="print-btn print-btn-secondary" onclick="window.close()">${closeLabel}</button>
    </div>
  </div>
  <div class="toolbar-spacer" aria-hidden="true"></div>`;

  const html = `<!DOCTYPE html>
<html lang="${escapeHtml(language ?? "es")}">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${escapeHtml(title)} — ${escapeHtml(projectName)}</title>
  <style>
    * { box-sizing: border-box; }
    body { margin: 0; font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; color: #111; background: #fff; }
    .print-toolbar {
      position: fixed; top: 0; left: 0; right: 0; z-index: 9999;
      background: #1a1a1a; color: #fff; padding: 12px 24px;
      display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 8px;
    }
    .print-toolbar-brand { color: ${amber}; font-weight: 700; font-size: 0.95rem; }
    .print-toolbar-actions { display: flex; gap: 12px; flex-wrap: wrap; }
    .print-btn { border: none; border-radius: 8px; cursor: pointer; font-size: 14px; padding: 8px 16px; min-height: 44px; }
    .print-btn-primary { background: ${amber}; color: #fff; padding-left: 20px; padding-right: 20px; }
    .print-btn-secondary { background: #444; color: #fff; }
    .toolbar-spacer { height: 56px; }
    .page { min-height: 100vh; display: flex; flex-direction: column; padding: 12mm; page-break-after: always; }
    .cover-page { min-height: auto; margin-bottom: 20px; page-break-after: always; }
    .cover-inner, .photo-inner { flex: 1; }
    .cover { justify-content: space-between; }
    .cover-inner { text-align: center; padding-top: 8mm; margin-bottom: 20px; }
    .logo { max-height: 72px; max-width: 200px; object-fit: contain; margin-bottom: 16px; }
    .company { font-size: 1.5rem; margin: 0 0 8px; }
    .machin-stamp { font-size: 1.25rem; font-weight: 700; letter-spacing: 0.05em; margin: 8px 0 20px; }
    .report-title { font-size: 1.35rem; margin: 0 0 12px; color: ${amber}; }
    .project-line { font-size: 1.1rem; margin: 12px 0; }
    .meta { font-size: 0.9rem; color: #444; margin: 6px 0; }
    .photo-inner { display: flex; flex-direction: column; }
    .photo-grid-1 .photo-cell { width: 100%; }
    .photo-grid-2 {
      display: grid; grid-template-columns: 1fr 1fr; gap: 12px; align-content: start;
    }
    .photo-grid-4 {
      display: grid; grid-template-columns: 1fr 1fr; grid-template-rows: auto auto; gap: 8px; align-content: start;
    }
    .photo-cell { min-width: 0; }
    .photo-grid-2 .seq, .photo-grid-4 .seq { font-size: 0.8rem; }
    .photo-grid-2 .line, .photo-grid-4 .line { font-size: 0.75rem; }
    .photo-grid-2 .notes, .photo-grid-4 .notes { font-size: 0.75rem; padding: 6px; }
    .seq { font-size: 1rem; font-weight: 700; color: ${amber}; margin: 0 0 8px; }
    .img-wrap { text-align: center; margin: 8px 0; }
    .photo-img { max-width: 100%; object-fit: contain; border: 1px solid #e5e5e5; border-radius: 8px; }
    .badges { display: flex; flex-wrap: wrap; gap: 6px; margin: 8px 0; }
    .badge { display: inline-block; padding: 4px 10px; border-radius: 9999px; font-size: 0.7rem; font-weight: 600; }
    .photo-grid-1 .badge { font-size: 0.75rem; }
    .badge.status { background: #f4f4f5; color: #3f3f46; }
    .line { font-size: 0.875rem; margin: 4px 0; }
    .notes { font-size: 0.875rem; color: #52525b; margin: 8px 0; padding: 10px; background: #fafafa; border-radius: 8px; border-left: 3px solid ${amber}; }
    .sig-block { margin-top: 8px; }
    .sig-img { max-height: 60px; max-width: 160px; object-fit: contain; }
    .sep { border: none; border-top: 1px solid #e4e4e7; margin: 12px 0 0; }
    a { color: ${amber}; }
    .page-footer { display: flex; justify-content: space-between; align-items: center; font-size: 0.75rem; color: #71717a; padding-top: 8px; border-top: 1px solid #e4e4e7; margin-top: auto; }
    .page-num { color: #71717a; }
    @media print {
      body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
      .print-toolbar, .toolbar-spacer { display: none !important; }
      .page { min-height: auto; page-break-after: always; }
      .page:last-child { page-break-after: auto; }
    }
    @page { size: ${pageSize}; margin: 10mm; }
  </style>
</head>
<body>
  ${toolbarHtml}
  ${coverHtml}
  ${photos.length ? photoPagesHtml : emptyPage}
  <script>window.onload = function() { window.focus(); };</script>
</body>
</html>`;

  const htmlContent = html;
  const blob = new Blob([htmlContent], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const win = window.open(url, "_blank");
  if (win) {
    win.addEventListener("load", () => {
      setTimeout(() => URL.revokeObjectURL(url), 10000);
    });
  } else {
    const a = document.createElement("a");
    a.href = url;
    a.download = `reporte-fotos-${Date.now()}.html`;
    a.click();
    setTimeout(() => URL.revokeObjectURL(url), 5000);
  }
}
