import { jsPDF } from "jspdf";
import { drawMachinProPdfFooter, drawPdfBrandedHeader } from "@/lib/pdfBranding";

export type DailyProductionPdfLine = {
  taskName: string;
  unitLabel: string;
  unitsCompleted: number;
  unitSellPrice: number;
  unitCostPrice: number;
  lineSell: number;
  lineCost: number;
  currency: string;
};

function L(labels: Record<string, string>, key: string, fallback: string): string {
  const v = labels[key];
  return typeof v === "string" && v.trim() ? v : fallback;
}

export async function generateDailyProductionPdf(opts: {
  labels: Record<string, string>;
  companyName: string;
  companyLogoUrl?: string | null;
  employeeName: string;
  projectName: string;
  reportDate: string;
  lines: DailyProductionPdfLine[];
  totalCost: number;
  totalSell: number;
  currency: string;
}): Promise<Blob> {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const R = (k: string, fb: string) => L(opts.labels, k, fb);

  let y = await drawPdfBrandedHeader(doc, { companyLogoUrl: opts.companyLogoUrl });

  doc.setFontSize(15);
  doc.setFont("helvetica", "bold");
  doc.text(R("production_report_title", "Daily production"), 105, y, { align: "center" });
  y += 8;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(opts.companyName, 14, y);
  y += 5;
  doc.text(`${R("personnel", "Employee")}: ${opts.employeeName}`, 14, y);
  y += 4;
  doc.text(`${R("project", "Project")}: ${opts.projectName}`, 14, y);
  y += 4;
  doc.text(`${R("date", "Date")}: ${opts.reportDate}`, 14, y);
  y += 8;

  const c0 = 14;
  const c1 = 62;
  const c2 = 82;
  const c3 = 108;
  const c4 = 138;
  const c5 = 162;

  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text(R("production_catalog_name", "Task"), c0, y);
  doc.text(R("production_catalog_unit", "Unit"), c1, y);
  doc.text(R("production_report_units", "Units"), c2, y);
  doc.text(R("production_catalog_sell_price", "Unit price"), c3, y);
  doc.text(R("production_pdf_line_total", "Total"), c5, y);
  y += 5;
  doc.line(14, y, 196, y);
  y += 4;
  doc.setFont("helvetica", "normal");

  const ensure = (need: number) => {
    if (y + need > 268) {
      doc.addPage();
      y = 20;
    }
  };

  for (const row of opts.lines) {
    ensure(10);
    const tLines = doc.splitTextToSize(row.taskName, 44);
    let ty = y;
    for (const tl of tLines) {
      doc.text(tl, c0, ty);
      ty += 3.5;
    }
    doc.text(row.unitLabel, c1, y);
    doc.text(String(row.unitsCompleted), c2, y);
    doc.text(`${row.currency} ${row.unitSellPrice.toFixed(4)}`, c3, y);
    doc.text(`${row.currency} ${row.lineSell.toFixed(2)}`, c5, y);
    y = Math.max(ty, y + 4);
  }

  ensure(18);
  doc.setFont("helvetica", "bold");
  doc.text(
    `${R("production_pdf_total_cost", "Total cost")}: ${opts.currency} ${opts.totalCost.toFixed(2)}`,
    14,
    y
  );
  y += 5;
  doc.text(
    `${R("production_pdf_total_sell", "Total sell")}: ${opts.currency} ${opts.totalSell.toFixed(2)}`,
    14,
    y
  );
  y += 10;

  ensure(22);
  doc.setFont("helvetica", "normal");
  doc.text(R("production_pdf_employee_signature", "Employee signature"), 14, y);
  y += 6;
  doc.line(14, y, 110, y);

  drawMachinProPdfFooter(doc, R("forms_pdf_footer", "Generated by MachinPro"));
  return doc.output("blob");
}
