/**
 * AH-31: PDF export for Operations → Project → General (jsPDF + autotable).
 */
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export type ProjectPdfTeamRow = { name: string; role: string; hours: number };
export type ProjectPdfCostRow = { description: string; quantity: number; amountCad: number };
export type ProjectPdfHazardRow = {
  description: string;
  severity: string;
  status: string;
  date: string;
};

export function buildProjectReportPdf(opts: {
  labels: Record<string, string>;
  companyName: string;
  projectName: string;
  projectTypeLabel: string;
  location: string;
  dateStart: string;
  dateEnd: string;
  lifecycleStatusLabel: string;
  budgetCad: number | null;
  spentCad: number | null;
  consumedPct: number | null;
  team: ProjectPdfTeamRow[];
  costs: ProjectPdfCostRow[];
  hazards: ProjectPdfHazardRow[];
  generationIso: string;
}): jsPDF {
  const L = (k: string, fb: string) => opts.labels[k] ?? fb;
  const doc = new jsPDF();
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 14;
  const footerText = `${L("pdf_footer_machinpro", "Generated by MachinPro · machin.pro")} · ${opts.generationIso.slice(0, 10)}`;

  const drawHeader = () => {
    doc.setFontSize(14);
    doc.text("MachinPro", margin, 18);
    doc.setFontSize(10);
    const co = opts.companyName || "—";
    doc.text(co, pageW - margin - doc.getTextWidth(co), 18);
    doc.setFontSize(13);
    doc.text(opts.projectName, margin, 30);
    doc.setFontSize(9);
    doc.text(`${L("pdf_generated_at", "Generated")}: ${opts.generationIso.slice(0, 16)}`, margin, 38);
  };

  drawHeader();

  let y = 48;
  doc.setFontSize(11);
  doc.text(L("pdf_section_general", "General information"), margin, y);

  autoTable(doc, {
    startY: y + 2,
    head: [[L("pdf_col_field", "Field"), L("pdf_col_value", "Value")]],
    body: [
      [L("projectFormTypeLabel", "Type"), opts.projectTypeLabel],
      [L("projectFormLocationLabel", "Location"), opts.location || "—"],
      [L("projectFormDateStart", "Start"), opts.dateStart],
      [L("projectFormDateEnd", "End"), opts.dateEnd],
      [L("projects_status_field", "Status"), opts.lifecycleStatusLabel],
      [L("projectFormBudgetTotal", "Budget"), opts.budgetCad != null ? `$${opts.budgetCad.toFixed(2)} CAD` : "—"],
      [
        L("project_budget_consumed_progress", "Spent"),
        opts.spentCad != null ? `$${opts.spentCad.toFixed(2)} CAD` : "—",
      ],
      [
        L("pdf_budget_execution_pct", "Budget execution %"),
        opts.consumedPct != null ? `${opts.consumedPct}%` : "—",
      ],
    ],
    styles: { fontSize: 9 },
    headStyles: { fillColor: [180, 120, 40] },
    margin: { left: margin, right: margin },
  });

  y = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? y + 40;
  y += 10;
  doc.text(L("pdf_section_team", "Assigned team"), margin, y);
  autoTable(doc, {
    startY: y + 2,
    head: [[L("pdf_col_name", "Name"), L("sessionRole", "Role"), L("pdf_col_hours", "Hours")]],
    body: opts.team.map((r) => [r.name, r.role, String(r.hours.toFixed(1))]),
    styles: { fontSize: 9 },
    headStyles: { fillColor: [180, 120, 40] },
    margin: { left: margin, right: margin },
  });

  y = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? y;
  y += 12;
  doc.text(L("pdf_section_costs", "Costs"), margin, y + 4);

  const costRows = opts.costs.map((r) => [
    r.description.slice(0, 80),
    String(r.quantity),
    `$${r.amountCad.toFixed(2)} CAD`,
  ]);
  const totalCosts = opts.costs.reduce((s, r) => s + r.amountCad, 0);

  autoTable(doc, {
    startY: y + 6,
    head: [
      [
        L("pdf_col_description", "Description"),
        L("pdf_col_quantity", "Qty"),
        L("pdf_col_cost", "Cost"),
      ],
    ],
    body:
      costRows.length > 0
        ? [...costRows, ["—", L("pdf_total", "Total"), `$${totalCosts.toFixed(2)} CAD`]]
        : [[L("pdf_no_cost_lines", "No cost lines"), "", ""]],
    styles: { fontSize: 9 },
    headStyles: { fillColor: [180, 120, 40] },
    margin: { left: margin, right: margin },
  });

  y = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? y;
  y += 12;
  doc.text(L("pdf_section_hazards_active", "Active hazards"), margin, y + 4);

  if (opts.hazards.length === 0) {
    autoTable(doc, {
      startY: y + 6,
      body: [[L("pdf_no_active_hazards", "No active hazards ✓")]],
      styles: { fontSize: 9 },
      margin: { left: margin, right: margin },
    });
  } else {
    autoTable(doc, {
      startY: y + 6,
      head: [
        [
          L("hazard_description", "Description"),
          L("hazard_severity", "Severity"),
          L("hazard_status", "Status"),
          L("date", "Date"),
        ],
      ],
      body: opts.hazards.map((h) => [
        h.description.slice(0, 120),
        h.severity,
        h.status,
        h.date,
      ]),
      styles: { fontSize: 8 },
      headStyles: { fillColor: [180, 60, 60] },
      margin: { left: margin, right: margin },
    });
  }

  const n = doc.getNumberOfPages();
  for (let i = 1; i <= n; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text(footerText, margin, pageH - 10);
    doc.setTextColor(0, 0, 0);
  }

  return doc;
}

export function slugProjectPdfName(projectName: string, isoDate: string): string {
  const safe = projectName.replace(/[^\w\s\-]/g, "").replace(/\s+/g, "_").slice(0, 80);
  const d = isoDate.slice(0, 10);
  return `${safe || "project"}-report-${d}.pdf`;
}
