/**
 * AH-32: Project report PDF (jsPDF + autotable) — multi-page layout, page footers.
 */
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export type ProjectPdfTeamRow = {
  name: string;
  role: string;
  hours: number;
  costCad: number;
};

export type ProjectPdfCostRow = {
  description: string;
  amountCad: number;
  date: string;
};

export type ProjectPdfHazardRow = {
  description: string;
  severity: string;
  status: string;
  date: string;
  reportedBy: string;
};

export type ProjectPdfCorrectiveRow = {
  description: string;
  status: string;
  dueDate: string;
};

const ORANGE: [number, number, number] = [249, 115, 22];

export function buildProjectReportPdf(opts: {
  labels: Record<string, string>;
  companyName: string;
  projectName: string;
  projectTypeLabel: string;
  location: string;
  dateStart: string;
  dateEnd: string;
  lifecycleStatusLabel: string;
  budgetCad: number | null;
  spentCad: number | null;
  consumedPct: number | null;
  team: ProjectPdfTeamRow[];
  costs: ProjectPdfCostRow[];
  hazards: ProjectPdfHazardRow[];
  correctives: ProjectPdfCorrectiveRow[];
  generationIso: string;
}): jsPDF {
  const L = (k: string, fb: string) => opts.labels[k] ?? fb;
  const doc = new jsPDF();
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 14;
  const genYmd = opts.generationIso.slice(0, 10);
  const genTime = opts.generationIso.slice(0, 16).replace("T", " ");
  const leftFooter = L("pdf_footer_machinpro", "Generated by MachinPro · machin.pro");
  const available =
    opts.budgetCad != null && opts.spentCad != null
      ? Math.max(0, Math.round((opts.budgetCad - opts.spentCad) * 100) / 100)
      : null;

  const drawPage1 = () => {
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text("MachinPro", margin, 16);
    doc.setFontSize(10);
    const co = opts.companyName || "—";
    doc.text(co, pageW - margin - doc.getTextWidth(co), 16);
    doc.setDrawColor(...ORANGE);
    doc.setLineWidth(0.5);
    doc.line(margin, 20, pageW - margin, 20);

    doc.setFontSize(16);
    doc.text(opts.projectName, margin, 32);
    doc.setFontSize(10);
    const sub = (L("project_pdf_subtitle", "Project Report · {{date}}") as string).replace("{{date}}", genYmd);
    doc.text(sub, margin, 40);

    let y = 50;
    doc.setFontSize(11);
    doc.text(L("pdf_section_general", "General information"), margin, y);
    y += 4;

    autoTable(doc, {
      startY: y,
      head: [[L("pdf_col_field", "Field"), L("pdf_col_value", "Value")]],
      body: [
        [L("projectFormTypeLabel", "Type"), opts.projectTypeLabel],
        [L("projectFormLocationLabel", "Location"), opts.location || "—"],
        [L("projectFormDateStart", "Start"), opts.dateStart || "—"],
        [L("projectFormDateEnd", "End"), opts.dateEnd || "—"],
        [L("projects_status_field", "Status"), opts.lifecycleStatusLabel],
      ],
      styles: { fontSize: 9 },
      headStyles: { fillColor: ORANGE },
      margin: { left: margin, right: margin },
    });
    y = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? y + 50;
    y += 8;
    doc.setFontSize(11);
    doc.text(L("pdf_section_budget", "Budget"), margin, y);
    y += 4;
    autoTable(doc, {
      startY: y,
      head: [[L("pdf_col_field", "Field"), L("pdf_col_value", "Value")]],
      body: [
        [L("pdf_budget_row_total", "Total"), opts.budgetCad != null ? fmtMoney(opts.budgetCad) : "—"],
        [L("pdf_budget_row_consumed", "Consumed"), opts.spentCad != null ? fmtMoney(opts.spentCad) : "—"],
        [L("pdf_budget_row_available", "Available"), available != null ? fmtMoney(available) : "—"],
        [
          L("pdf_budget_row_pct_executed", "% executed"),
          opts.consumedPct != null ? `${opts.consumedPct}%` : "—",
        ],
      ],
      styles: { fontSize: 9 },
      headStyles: { fillColor: ORANGE },
      margin: { left: margin, right: margin },
    });
  };

  drawPage1();

  doc.addPage();
  doc.setFontSize(12);
  doc.text(L("pdf_section_team", "Team"), margin, 18);
  const teamTotalH = opts.team.reduce((s, r) => s + r.hours, 0);
  const teamTotalC = opts.team.reduce((s, r) => s + r.costCad, 0);
  autoTable(doc, {
    startY: 22,
    head: [
      [
        L("pdf_col_name", "Name"),
        L("sessionRole", "Role"),
        L("pdf_col_hours", "Hours"),
        L("pdf_col_cost", "Cost"),
      ],
    ],
    body: [
      ...opts.team.map((r) => [
        r.name.slice(0, 40),
        r.role.slice(0, 24),
        String(Math.round(r.hours * 10) / 10),
        fmtMoney(r.costCad),
      ]),
      [
        L("pdf_total", "Total"),
        "",
        String(Math.round(teamTotalH * 10) / 10),
        fmtMoney(Math.round(teamTotalC * 100) / 100),
      ],
    ],
    styles: { fontSize: 9 },
    headStyles: { fillColor: ORANGE },
    margin: { left: margin, right: margin },
  });

  let y2 = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? 80;
  y2 += 12;
  doc.setFontSize(12);
  doc.text(L("pdf_section_project_costs", "Project costs"), margin, y2);
  const costSum = opts.costs.reduce((s, r) => s + r.amountCad, 0);
  autoTable(doc, {
    startY: y2 + 4,
    head: [
      [
        L("pdf_col_description", "Description"),
        L("pdf_col_amount", "Amount"),
        L("pdf_col_date", "Date"),
      ],
    ],
    body:
      opts.costs.length > 0
        ? [
            ...opts.costs.map((r) => [
              r.description.slice(0, 72),
              fmtMoney(r.amountCad),
              r.date,
            ]),
            [L("pdf_total", "Total"), fmtMoney(Math.round(costSum * 100) / 100), ""],
          ]
        : [[L("pdf_no_cost_lines", "No cost lines"), "", ""]],
    styles: { fontSize: 9 },
    headStyles: { fillColor: ORANGE },
    margin: { left: margin, right: margin },
  });

  doc.addPage();
  doc.setFontSize(12);
  doc.text(L("pdf_section_hazards_active", "Active hazards"), margin, 18);
  let y3 = 22;
  if (opts.hazards.length === 0) {
    autoTable(doc, {
      startY: y3,
      body: [[L("pdf_no_active_hazards", "No active hazards ✓")]],
      styles: { fontSize: 9 },
      margin: { left: margin, right: margin },
    });
  } else {
    autoTable(doc, {
      startY: y3,
      head: [
        [
          L("hazard_description", "Description"),
          L("hazard_severity", "Severity"),
          L("hazard_status", "Status"),
          L("pdf_col_date", "Date"),
          L("pdf_col_reported_by", "Reported by"),
        ],
      ],
      body: opts.hazards.map((h) => [
        h.description.slice(0, 80),
        h.severity,
        h.status,
        h.date,
        h.reportedBy.slice(0, 28),
      ]),
      styles: { fontSize: 8 },
      headStyles: { fillColor: [220, 80, 80] },
      margin: { left: margin, right: margin },
    });
  }

  y3 = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? 60;
  y3 += 14;
  doc.setFontSize(12);
  doc.text(L("pdf_section_corrective_actions", "Corrective actions"), margin, y3);

  if (opts.correctives.length === 0) {
    autoTable(doc, {
      startY: y3 + 4,
      body: [[L("pdf_no_pending_corrective", "No pending corrective actions ✓")]],
      styles: { fontSize: 9 },
      margin: { left: margin, right: margin },
    });
  } else {
    autoTable(doc, {
      startY: y3 + 4,
      head: [
        [
          L("pdf_col_description", "Description"),
          L("hazard_status", "Status"),
          L("pdf_col_due_date", "Due date"),
        ],
      ],
      body: opts.correctives.map((c) => [
        c.description.slice(0, 100),
        c.status,
        c.dueDate || "—",
      ]),
      styles: { fontSize: 9 },
      headStyles: { fillColor: ORANGE },
      margin: { left: margin, right: margin },
    });
  }

  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    const pageOf = (L("pdf_page_of", "Page {{x}} of {{y}}") as string)
      .replace("{{x}}", String(i))
      .replace("{{y}}", String(totalPages));
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text(leftFooter, margin, pageH - 10);
    const rw = doc.getTextWidth(pageOf);
    doc.text(pageOf, pageW - margin - rw, pageH - 10);
    doc.setFontSize(7);
    const dw = doc.getTextWidth(genTime);
    doc.text(genTime, (pageW - dw) / 2, pageH - 6);
    doc.setTextColor(0, 0, 0);
  }

  return doc;
}

function fmtMoney(n: number): string {
  return `$${n.toFixed(2)} CAD`;
}

export function slugProjectPdfName(projectName: string, isoDate: string): string {
  const safe =
    projectName
      .replace(/[^\w\s\-]/gu, "")
      .trim()
      .replace(/\s+/g, "-")
      .replace(/-+/g, "-")
      .slice(0, 80) || "project";
  const d = isoDate.slice(0, 10);
  return `${safe}-report-${d}.pdf`;
}
