/** Shared country lists for Settings, onboarding, and public register (order: CA/US/MX, LATAM, GB, EU, CH, OC, other). */

export type RegionalCountryDefaults = {
  currency: string;
  measurementSystem: "metric" | "imperial";
  taxIdLabel: string;
};

export const REGIONAL_COUNTRY_DEFAULTS: Record<string, RegionalCountryDefaults> = {
  CA: { currency: "CAD", measurementSystem: "metric", taxIdLabel: "BN / GST Number" },
  US: { currency: "USD", measurementSystem: "imperial", taxIdLabel: "EIN" },
  MX: { currency: "MXN", measurementSystem: "metric", taxIdLabel: "RFC" },
  AR: { currency: "ARS", measurementSystem: "metric", taxIdLabel: "CUIT" },
  BR: { currency: "BRL", measurementSystem: "metric", taxIdLabel: "CNPJ" },
  CL: { currency: "CLP", measurementSystem: "metric", taxIdLabel: "RUT" },
  CO: { currency: "COP", measurementSystem: "metric", taxIdLabel: "NIT" },
  CR: { currency: "CRC", measurementSystem: "metric", taxIdLabel: "Cédula jurídica" },
  GT: { currency: "GTQ", measurementSystem: "metric", taxIdLabel: "NIT" },
  HN: { currency: "HNL", measurementSystem: "metric", taxIdLabel: "RTN" },
  NI: { currency: "NIO", measurementSystem: "metric", taxIdLabel: "RUC" },
  PA: { currency: "PAB", measurementSystem: "metric", taxIdLabel: "RUC" },
  PE: { currency: "PEN", measurementSystem: "metric", taxIdLabel: "RUC" },
  SV: { currency: "USD", measurementSystem: "metric", taxIdLabel: "NIT" },
  UY: { currency: "UYU", measurementSystem: "metric", taxIdLabel: "RUT" },
  GB: { currency: "GBP", measurementSystem: "imperial", taxIdLabel: "VAT Number" },
  EU: { currency: "EUR", measurementSystem: "metric", taxIdLabel: "VAT Number" },
  ES: { currency: "EUR", measurementSystem: "metric", taxIdLabel: "CIF/NIF" },
  FR: { currency: "EUR", measurementSystem: "metric", taxIdLabel: "SIRET" },
  DE: { currency: "EUR", measurementSystem: "metric", taxIdLabel: "Steuernummer" },
  IT: { currency: "EUR", measurementSystem: "metric", taxIdLabel: "Partita IVA" },
  PT: { currency: "EUR", measurementSystem: "metric", taxIdLabel: "NIF" },
  NL: { currency: "EUR", measurementSystem: "metric", taxIdLabel: "BTW-nummer" },
  PL: { currency: "PLN", measurementSystem: "metric", taxIdLabel: "NIP" },
  SE: { currency: "SEK", measurementSystem: "metric", taxIdLabel: "Organisationsnummer" },
  NO: { currency: "NOK", measurementSystem: "metric", taxIdLabel: "Organisasjonsnummer" },
  DK: { currency: "DKK", measurementSystem: "metric", taxIdLabel: "CVR-nummer" },
  CH: { currency: "CHF", measurementSystem: "metric", taxIdLabel: "UID" },
  BE: { currency: "EUR", measurementSystem: "metric", taxIdLabel: "BTW" },
  AT: { currency: "EUR", measurementSystem: "metric", taxIdLabel: "UID" },
  IE: { currency: "EUR", measurementSystem: "metric", taxIdLabel: "VAT" },
  CZ: { currency: "CZK", measurementSystem: "metric", taxIdLabel: "IČO" },
  HU: { currency: "HUF", measurementSystem: "metric", taxIdLabel: "Adószám" },
  RO: { currency: "RON", measurementSystem: "metric", taxIdLabel: "CUI" },
  BG: { currency: "BGN", measurementSystem: "metric", taxIdLabel: "UIC" },
  HR: { currency: "HRK", measurementSystem: "metric", taxIdLabel: "OIB" },
  GR: { currency: "EUR", measurementSystem: "metric", taxIdLabel: "ΑΦΜ" },
  TR: { currency: "TRY", measurementSystem: "metric", taxIdLabel: "VKN" },
  AU: { currency: "AUD", measurementSystem: "metric", taxIdLabel: "ABN" },
  NZ: { currency: "NZD", measurementSystem: "metric", taxIdLabel: "IRD Number" },
  SG: { currency: "SGD", measurementSystem: "metric", taxIdLabel: "UEN" },
  JP: { currency: "JPY", measurementSystem: "metric", taxIdLabel: "法人番号" },
  KR: { currency: "KRW", measurementSystem: "metric", taxIdLabel: "사업자등록번호" },
  IN: { currency: "INR", measurementSystem: "metric", taxIdLabel: "GSTIN" },
  ZA: { currency: "ZAR", measurementSystem: "metric", taxIdLabel: "VAT" },
};

export const REGIONAL_COUNTRIES: { code: string; flag: string; name: string }[] = [
  { code: "CA", flag: "🇨🇦", name: "Canada" },
  { code: "US", flag: "🇺🇸", name: "United States" },
  { code: "MX", flag: "🇲🇽", name: "México" },
  { code: "AR", flag: "🇦🇷", name: "Argentina" },
  { code: "BR", flag: "🇧🇷", name: "Brazil" },
  { code: "CL", flag: "🇨🇱", name: "Chile" },
  { code: "CO", flag: "🇨🇴", name: "Colombia" },
  { code: "CR", flag: "🇨🇷", name: "Costa Rica" },
  { code: "GT", flag: "🇬🇹", name: "Guatemala" },
  { code: "HN", flag: "🇭🇳", name: "Honduras" },
  { code: "NI", flag: "🇳🇮", name: "Nicaragua" },
  { code: "PA", flag: "🇵🇦", name: "Panama" },
  { code: "PE", flag: "🇵🇪", name: "Peru" },
  { code: "SV", flag: "🇸🇻", name: "El Salvador" },
  { code: "UY", flag: "🇺🇾", name: "Uruguay" },
  { code: "GB", flag: "🇬🇧", name: "United Kingdom" },
  { code: "ES", flag: "🇪🇸", name: "España" },
  { code: "FR", flag: "🇫🇷", name: "France" },
  { code: "DE", flag: "🇩🇪", name: "Deutschland" },
  { code: "IT", flag: "🇮🇹", name: "Italia" },
  { code: "PT", flag: "🇵🇹", name: "Portugal" },
  { code: "NL", flag: "🇳🇱", name: "Nederland" },
  { code: "PL", flag: "🇵🇱", name: "Polska" },
  { code: "SE", flag: "🇸🇪", name: "Sverige" },
  { code: "NO", flag: "🇳🇴", name: "Norge" },
  { code: "DK", flag: "🇩🇰", name: "Danmark" },
  { code: "CH", flag: "🇨🇭", name: "Schweiz" },
  { code: "BE", flag: "🇧🇪", name: "Belgium" },
  { code: "AT", flag: "🇦🇹", name: "Österreich" },
  { code: "IE", flag: "🇮🇪", name: "Ireland" },
  { code: "CZ", flag: "🇨🇿", name: "Česká republika" },
  { code: "HU", flag: "🇭🇺", name: "Magyarország" },
  { code: "RO", flag: "🇷🇴", name: "România" },
  { code: "BG", flag: "🇧🇬", name: "България" },
  { code: "HR", flag: "🇭🇷", name: "Hrvatska" },
  { code: "GR", flag: "🇬🇷", name: "Ελλάδα" },
  { code: "TR", flag: "🇹🇷", name: "Türkiye" },
  { code: "AU", flag: "🇦🇺", name: "Australia" },
  { code: "NZ", flag: "🇳🇿", name: "New Zealand" },
];

/** IANA default timezone for onboarding step 1 (subset; falls back to resolveUserTimezone). */
export const REGIONAL_TZ_BY_COUNTRY: Record<string, string> = {
  CA: "America/Toronto",
  US: "America/New_York",
  MX: "America/Mexico_City",
  AR: "America/Argentina/Buenos_Aires",
  BR: "America/Sao_Paulo",
  CL: "America/Santiago",
  CO: "America/Bogota",
  CR: "America/Costa_Rica",
  GT: "America/Guatemala",
  HN: "America/Tegucigalpa",
  NI: "America/Managua",
  PA: "America/Panama",
  PE: "America/Lima",
  SV: "America/El_Salvador",
  UY: "America/Montevideo",
  GB: "Europe/London",
  ES: "Europe/Madrid",
  FR: "Europe/Paris",
  DE: "Europe/Berlin",
  IT: "Europe/Rome",
  PT: "Europe/Lisbon",
  NL: "Europe/Amsterdam",
  PL: "Europe/Warsaw",
  SE: "Europe/Stockholm",
  NO: "Europe/Oslo",
  DK: "Europe/Copenhagen",
  CH: "Europe/Zurich",
  BE: "Europe/Brussels",
  AT: "Europe/Vienna",
  IE: "Europe/Dublin",
  CZ: "Europe/Prague",
  HU: "Europe/Budapest",
  RO: "Europe/Bucharest",
  BG: "Europe/Sofia",
  HR: "Europe/Zagreb",
  GR: "Europe/Athens",
  TR: "Europe/Istanbul",
  AU: "Australia/Sydney",
  NZ: "Pacific/Auckland",
  SG: "Asia/Singapore",
  JP: "Asia/Tokyo",
  KR: "Asia/Seoul",
  IN: "Asia/Kolkata",
  ZA: "Africa/Johannesburg",
};
