/**
 * AH-30: Safety module PDF summary.
 */
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export type SafetyPdfHazardRow = { description: string; severity: string; status: string; date: string; owner: string };
export type SafetyPdfCaRow = { description: string; status: string; due: string };

export function buildSafetyReportPdf(opts: {
  labels: Record<string, string>;
  companyName: string;
  totals: { hazards: number; active: number; resolved: number };
  hazards: SafetyPdfHazardRow[];
  corrective: SafetyPdfCaRow[];
  swpLines: string[];
  certLines: string[];
  generationIso: string;
}): jsPDF {
  const L = (k: string, fb: string) => opts.labels[k] ?? fb;
  const doc = new jsPDF();
  doc.setFontSize(16);
  doc.text("MachinPro", 14, 18);
  doc.setFontSize(10);
  doc.text(opts.companyName, 14, 26);
  doc.setFontSize(9);
  doc.text(`${L("pdf_generated_at", "Generated")}: ${opts.generationIso.slice(0, 16)}`, 14, 34);

  doc.setFontSize(11);
  doc.text(L("pdf_safety_summary", "Summary"), 14, 46);
  autoTable(doc, {
    startY: 48,
    head: [[L("pdf_metric", "Metric"), L("pdf_col_value", "Value")]],
    body: [
      [L("pdf_total_hazards", "Total hazards"), String(opts.totals.hazards)],
      [L("pdf_active_hazards", "Active"), String(opts.totals.active)],
      [L("pdf_resolved_hazards", "Resolved"), String(opts.totals.resolved)],
    ],
    styles: { fontSize: 9 },
    headStyles: { fillColor: [180, 60, 60] },
  });

  let y = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? 70;
  y += 10;
  doc.text(L("pdf_section_hazards", "Hazards"), 14, y);
  autoTable(doc, {
    startY: y + 2,
    head: [
      [
        L("hazard_description", "Description"),
        L("hazard_severity", "Severity"),
        L("hazard_status", "Status"),
        L("date", "Date"),
        L("pdf_owner", "Owner"),
      ],
    ],
    body: opts.hazards.map((h) => [
      h.description.slice(0, 100),
      h.severity,
      h.status,
      h.date,
      h.owner,
    ]),
    styles: { fontSize: 7 },
    headStyles: { fillColor: [180, 60, 60] },
  });
  y = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? y;
  y += 12;
  doc.text(L("pdf_section_corrective", "Corrective actions"), 14, y);
  autoTable(doc, {
    startY: y + 2,
    head: [[L("pdf_col_description", "Description"), L("hazard_status", "Status"), L("pdf_due", "Due")]],
    body: opts.corrective.map((c) => [c.description.slice(0, 100), c.status, c.due]),
    styles: { fontSize: 8 },
    headStyles: { fillColor: [180, 120, 40] },
  });
  y = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? y;
  y += 12;
  doc.text(L("pdf_section_swp", "Safe work procedures"), 14, y);
  autoTable(doc, {
    startY: y + 2,
    head: [[L("pdf_col_details", "Details")]],
    body: opts.swpLines.map((s) => [s]),
    styles: { fontSize: 8 },
    headStyles: { fillColor: [80, 120, 180] },
  });
  y = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? y;
  y += 12;
  doc.text(L("pdf_section_certs_expiring", "Certificates expiring soon"), 14, y);
  autoTable(doc, {
    startY: y + 2,
    head: [[L("pdf_col_details", "Details")]],
    body: opts.certLines.map((s) => [s]),
    styles: { fontSize: 8 },
    headStyles: { fillColor: [80, 160, 120] },
  });

  doc.setFontSize(8);
  doc.text(`${L("pdf_footer_machinpro", "Generated by MachinPro · machin.pro")}`, 14, doc.internal.pageSize.height - 10);

  return doc;
}

export function slugSafetyPdfName(companyName: string, isoDate: string): string {
  const safe = companyName.replace(/[^\w\s\-]/g, "").replace(/\s+/g, "_").slice(0, 60);
  const d = isoDate.slice(0, 10);
  return `${safe || "company"}-safety-report-${d}.pdf`;
}
